# Generated by Django 5.2.6 on 2025-09-29 10:51

from django.db import migrations


def convert_admin_log_user_to_uuid(apps, schema_editor):
    # Execute only on PostgreSQL where ALTER TYPE operations are valid
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DELETE FROM django_admin_log;")
        cursor.execute("ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fkey;")
        cursor.execute("ALTER TABLE django_admin_log ALTER COLUMN user_id TYPE UUID USING user_id::text::UUID;")
        cursor.execute(
            "ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_customuser(id) DEFERRABLE INITIALLY DEFERRED;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.RunPython(convert_admin_log_user_to_uuid, migrations.RunPython.noop),
    ]
