# Generated by Django 5.2.6 on 2025-09-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        # Clear the admin log table to avoid data conflicts during type conversion
        migrations.RunSQL(
            "DELETE FROM django_admin_log;",
            reverse_sql="-- No reverse operation needed"
        ),
        # Drop the foreign key constraint first
        migrations.RunSQL(
            "ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fkey;",
            reverse_sql="-- No reverse operation needed"
        ),
        # Alter the user_id column to UUID type
        migrations.RunSQL(
            "ALTER TABLE django_admin_log ALTER COLUMN user_id TYPE UUID USING user_id::text::UUID;",
            reverse_sql="-- No reverse operation needed"
        ),
        # Recreate the foreign key constraint
        migrations.RunSQL(
            "ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_customuser(id) DEFERRABLE INITIALLY DEFERRED;",
            reverse_sql="-- No reverse operation needed"
        ),
    ]
