# Generated by Django 5.2.6 on 2025-09-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250929_1051'),
    ]

    operations = [
        # Fix users_customuser_groups table
        migrations.RunSQL(
            "ALTER TABLE users_customuser_groups DROP CONSTRAINT IF EXISTS users_customuser_groups_customuser_id_fkey;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_customuser_groups ALTER COLUMN customuser_id TYPE UUID USING customuser_id::text::UUID;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_customuser_groups ADD CONSTRAINT users_customuser_groups_customuser_id_fkey FOREIGN KEY (customuser_id) REFERENCES users_customuser(id) DEFERRABLE INITIALLY DEFERRED;",
            reverse_sql="-- No reverse operation needed"
        ),
        
        # Fix users_customuser_user_permissions table
        migrations.RunSQL(
            "ALTER TABLE users_customuser_user_permissions DROP CONSTRAINT IF EXISTS users_customuser_user_permissions_customuser_id_fkey;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_customuser_user_permissions ALTER COLUMN customuser_id TYPE UUID USING customuser_id::text::UUID;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_customuser_user_permissions ADD CONSTRAINT users_customuser_user_permissions_customuser_id_fkey FOREIGN KEY (customuser_id) REFERENCES users_customuser(id) DEFERRABLE INITIALLY DEFERRED;",
            reverse_sql="-- No reverse operation needed"
        ),
    ]
