# Generated by Django 5.2.6 on 2025-11-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='field',
            new_name='fields_fiel_envelop_494744_idx',
            old_name='field_env_doc_idx',
        ),
        migrations.RenameIndex(
            model_name='field',
            new_name='fields_fiel_documen_d9fb80_idx',
            old_name='field_doc_page_idx',
        ),
        migrations.RenameIndex(
            model_name='field',
            new_name='fields_fiel_assigne_463b95_idx',
            old_name='field_assigned_signer_idx',
        ),
    ]
