# Generated by Django 5.2.6 on 2025-09-16 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the envelope.', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='draft', help_text='Current status of the envelope in the signing workflow.', max_length=20)),
                ('signing_order', models.JSONField(blank=True, default=list, help_text="List of signers in order: [{'signer_id': 'uuid', 'order': 1}, ...]")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the envelope was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the envelope was last updated.')),
            ],
            options={
                'verbose_name': 'Envelope',
                'verbose_name_plural': 'Envelopes',
                'ordering': ['-created_at'],
            },
        ),
    ]
