# Generated by Django 5.2.6 on 2025-09-16 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('documents', '0002_initial'),
        ('envelopes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='creator',
            field=models.ForeignKey(help_text='The user who created this envelope.', on_delete=django.db.models.deletion.CASCADE, related_name='created_envelopes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envelope',
            name='document',
            field=models.ForeignKey(help_text='The document that this envelope contains for signing.', on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='documents.document'),
        ),
    ]
