# Generated by Django 5.2.6 on 2025-09-17 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_documents_d_owner_i_683479_idx_and_more'),
        ('envelopes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='envelope',
            index=models.Index(fields=['creator', 'status'], name='envelopes_e_creator_8b1593_idx'),
        ),
        migrations.AddIndex(
            model_name='envelope',
            index=models.Index(fields=['status'], name='envelopes_e_status_05ed01_idx'),
        ),
        migrations.AddIndex(
            model_name='envelope',
            index=models.Index(fields=['created_at'], name='envelopes_e_created_c9323f_idx'),
        ),
    ]
