# Generated by Django 5.2.6 on 2025-10-07 09:37

from django.db import migrations, models


def populate_envelope_names(apps, schema_editor):
    """
    Populate the name field for existing envelopes with their document names.
    """
    Envelope = apps.get_model('envelopes', 'Envelope')
    
    for envelope in Envelope.objects.select_related('document').all():
        envelope.name = envelope.document.file_name
        envelope.save(update_fields=['name'])


def reverse_populate_envelope_names(apps, schema_editor):
    """
    Reverse migration - set all envelope names to default.
    """
    Envelope = apps.get_model('envelopes', 'Envelope')
    
    for envelope in Envelope.objects.all():
        envelope.name = "Untitled Envelope"
        envelope.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0003_envelope_envelopes_e_creator_8b1593_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='name',
            field=models.CharField(
                default='Untitled Envelope',
                help_text='Name of the envelope, derived from the document name.',
                max_length=255
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            populate_envelope_names,
            reverse_populate_envelope_names,
            atomic=True,
        ),
        migrations.AddIndex(
            model_name='envelope',
            index=models.Index(fields=['name'], name='envelopes_e_name_f3a5c1_idx'),
        ),
    ]
