# Generated by Django 5.2.6 on 2025-10-13 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_signed_file_url'),
        ('envelopes', '0005_rename_sent_to_pending_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvelopeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the EnvelopeDocument link.', primary_key=True, serialize=False)),
                ('order', models.IntegerField(help_text='The order of this document within the envelope (1-based).')),
                ('signer_document_positions', models.JSONField(blank=True, default=list, help_text="List of signer positions for this document: [{'signer_id': 'uuid', 'position': {'page': 1, 'x': 100, 'y': 100, 'width': 120, 'height': 40}}, ...]")),
            ],
            options={
                'verbose_name': 'Envelope Document',
                'verbose_name_plural': 'Envelope Documents',
                'ordering': ['order'],
            },
        ),
        migrations.RenameIndex(
            model_name='envelope',
            new_name='envelopes_e_name_021e35_idx',
            old_name='envelopes_e_name_f3a5c1_idx',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='document',
        ),
        migrations.AlterField(
            model_name='envelope',
            name='name',
            field=models.CharField(blank=True, help_text="User-defined name of the envelope. Defaults to 'Untitled Envelope' + timestamp.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='signing_order',
            field=models.JSONField(blank=True, default=list, help_text="List of signers in order: [{'signer_id': 'uuid', 'order': 1}, ...]. Document-specific positions are in EnvelopeDocument."),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='draft', help_text='Current status of the envelope in the signing workflow.', max_length=20),
        ),
        migrations.AddField(
            model_name='envelopedocument',
            name='document',
            field=models.ForeignKey(help_text='The document included in this envelope.', on_delete=django.db.models.deletion.CASCADE, related_name='envelopedocument_set', to='documents.document'),
        ),
        migrations.AddField(
            model_name='envelopedocument',
            name='envelope',
            field=models.ForeignKey(help_text='The envelope this document belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='envelopedocument_set', to='envelopes.envelope'),
        ),
        migrations.AddIndex(
            model_name='envelopedocument',
            index=models.Index(fields=['envelope', 'order'], name='envelopes_e_envelop_497ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='envelopedocument',
            index=models.Index(fields=['document'], name='envelopes_e_documen_8abfbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='envelopedocument',
            unique_together={('envelope', 'document'), ('envelope', 'order')},
        ),
    ]
