# Generated by Django 5.2.7 on 2025-11-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0006_envelopedocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or notes for recipients about this envelope.', null=True),
        ),
    ]
