# Generated by Django 5.2.6 on 2025-11-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0007_envelope_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='pdf_lock_password',
            field=models.CharField(blank=True, help_text='Password applied to lock signed PDFs once the envelope is completed.', max_length=128, null=True),
        ),
    ]
