# Generated by Django 5.2.6 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0008_envelope_pdf_lock_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='pdf_password_protection_enabled',
            field=models.BooleanField(default=True, help_text='If True, signed PDFs are password-protected when the envelope is completed.'),
        ),
    ]

