# Generated by Django 5.2.6 on 2025-09-15 19:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the document', primary_key=True, serialize=False)),
                ('file_url', models.CharField(help_text='File path or S3 URL where the document is stored', max_length=500)),
                ('file_name', models.CharField(help_text='Original name of the uploaded file', max_length=255)),
                ('file_size', models.IntegerField(help_text='Size of the file in bytes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='draft', help_text='Current status of the document in the signing workflow', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the document was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the document was last updated')),
                ('owner', models.ForeignKey(help_text='User who owns this document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
