# Generated by Django 5.2.6 on 2025-09-20 12:10

from django.db import migrations, connection


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_documents_d_owner_i_683479_idx_and_more'),
    ]

    # Skip PostgreSQL-specific SQL when using SQLite (tests)
    if connection.vendor == 'sqlite':
        operations = []
    else:
        operations = [
            migrations.RunSQL(
                sql="ALTER TABLE documents_document ALTER COLUMN owner_id SET DATA TYPE uuid USING gen_random_uuid();",
                reverse_sql="ALTER TABLE documents_document ALTER COLUMN owner_id SET DATA TYPE bigint USING 1;"
            ),
        ]
