# Generated by Django 5.2.6 on 2025-09-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_documents_d_owner_i_683479_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL: Convert owner_id from bigint to UUID
            # Since there are no documents in the table yet, we can safely convert the column type
            sql="ALTER TABLE documents_document ALTER COLUMN owner_id SET DATA TYPE uuid USING gen_random_uuid();",
            # Reverse SQL: Convert back to bigint
            reverse_sql="ALTER TABLE documents_document ALTER COLUMN owner_id SET DATA TYPE bigint USING 1;"
        ),
    ]
