# Generated by Django 5.2.6 on 2025-09-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_convert_owner_id_to_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signed_file_url',
            field=models.CharField(blank=True, help_text='File path or URL to the signed PDF version if available', max_length=500, null=True),
        ),
    ]
