# Generated by Django 5.2.6 on 2026-07-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_signed_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.CharField(help_text='File path or S3 URL where the document is stored', max_length=2048),
        ),
        migrations.AlterField(
            model_name='document',
            name='signed_file_url',
            field=models.CharField(blank=True, help_text='File path or URL to the signed PDF version if available', max_length=2048, null=True),
        ),
    ]
