# Generated by Django 5.2.6 on 2026-08-03 08:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the integration.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human label, e.g. "HR Portal".', max_length=255)),
                ('client_id', models.CharField(editable=False, help_text='Public opaque identifier for this integration.', max_length=64, unique=True)),
                ('client_secret_hash', models.CharField(editable=False, help_text='Django password hash of the client secret. Never store the raw secret.', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-disable without deleting the integration.')),
                ('allow_jit_user_create', models.BooleanField(default=True, help_text='When True, token exchange may create users that do not yet exist.')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal ops notes.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff user who registered this integration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
