# Generated by Django 5.2.6 on 2026-08-03 09:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='allowed_cidrs',
            field=models.JSONField(blank=True, default=list, help_text='Optional IP allowlist for token exchange. JSON list of IPs or CIDRs, e.g. ["203.0.113.0/24", "198.51.100.10"]. Empty list = allow all.'),
        ),
        migrations.CreateModel(
            name='IntegrationUserLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this link row.', primary_key=True, serialize=False)),
                ('external_user_id', models.CharField(help_text="Partner application's stable user identifier.", max_length=255)),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this link was first created.')),
                ('integration', models.ForeignKey(help_text='Integration that owns this partner-user mapping.', on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='integrations.integration')),
                ('user', models.ForeignKey(help_text='Resolved e-sign user for this partner identity.', on_delete=django.db.models.deletion.CASCADE, related_name='integration_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration user link',
                'verbose_name_plural': 'Integration user links',
                'ordering': ['-linked_at'],
                'constraints': [models.UniqueConstraint(fields=('integration', 'external_user_id'), name='uniq_integration_external_user_id'), models.UniqueConstraint(fields=('integration', 'user'), name='uniq_integration_user')],
            },
        ),
    ]
