# Generated by Django 5.2.6 on 2026-08-04 12:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0012_seed_self_signed_envelope_status'),
        ('integrations', '0002_phase3_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEnvelopeOrigin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('envelope', models.OneToOneField(help_text='Envelope created or sent via an integration JWT.', on_delete=django.db.models.deletion.CASCADE, related_name='integration_origin', to='envelopes.envelope')),
                ('integration', models.ForeignKey(help_text='Integration that originated this envelope.', on_delete=django.db.models.deletion.CASCADE, related_name='envelope_origins', to='integrations.integration')),
            ],
            options={
                'verbose_name': 'Integration envelope origin',
                'verbose_name_plural': 'Integration envelope origins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationWebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='HTTPS URL that receives signed POST payloads.', max_length=2048)),
                ('description', models.CharField(blank=True, default='', help_text='Optional ops label for this endpoint.', max_length=255)),
                ('signing_secret_encrypted', models.TextField(editable=False, help_text='Encrypted signing secret used for HMAC. Never log decoded value.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-disable without deleting delivery history.')),
                ('enabled_events', models.JSONField(blank=True, default=list, help_text='Event types to deliver, e.g. ["envelope.sent", "envelope.completed"]. Empty list means all supported events.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(help_text='Integration that owns this webhook endpoint.', on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='integrations.integration')),
            ],
            options={
                'verbose_name': 'Integration webhook endpoint',
                'verbose_name_plural': 'Integration webhook endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Value of the Idempotency-Key request header.', max_length=255)),
                ('scope', models.CharField(help_text='Logical endpoint scope, e.g. envelopes.create.', max_length=128)),
                ('response_status', models.PositiveIntegerField()),
                ('response_body', models.JSONField(help_text='Snapshot of the successful JSON response body.')),
                ('envelope_id', models.UUIDField(blank=True, help_text='Envelope created/sent when applicable.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idempotency record',
                'verbose_name_plural': 'Idempotency records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['envelope_id'], name='integration_envelop_9503ff_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'key', 'scope'), name='uniq_idempotency_user_key_scope')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationWebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('envelope_id', models.UUIDField(blank=True, help_text='Related envelope id when applicable.', null=True)),
                ('payload', models.JSONField(help_text='JSON body that was (or will be) POSTed. No secrets.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body_excerpt', models.CharField(blank=True, default='', help_text='Truncated response body for ops; never includes our secrets.', max_length=512)),
                ('last_error', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.integrationwebhookendpoint')),
            ],
            options={
                'verbose_name': 'Integration webhook delivery',
                'verbose_name_plural': 'Integration webhook deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='integration_event_t_0c6e73_idx'), models.Index(fields=['envelope_id'], name='integration_envelop_31726c_idx')],
            },
        ),
    ]
