"""
Django settings for esign project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
from decouple import config, Csv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default=None)
if SECRET_KEY is None:
    # Allow missing SECRET_KEY in local/dev, but warn loudly
    import warnings
    warnings.warn(
        "SECRET_KEY is not set in environment. Using insecure default key for development only!",
        UserWarning
    )
    SECRET_KEY = 'django-insecure-placeholder-secret-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool, default=None)
if DEBUG is None:
    DEBUG = True

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv(), default=None)
if ALLOWED_HOSTS is None:
    # Sensible default for local development
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Sentry SDK for error tracking (only in production)
SENTRY_DSN = config('SENTRY_DSN', default=None)
if SENTRY_DSN and not DEBUG:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.redis import RedisIntegration
    
    sentry_traces_sample_rate = config('SENTRY_TRACES_SAMPLE_RATE', cast=float, default=None)
    if sentry_traces_sample_rate is None:
        sentry_traces_sample_rate = 0.1

    sentry_environment = config('SENTRY_ENVIRONMENT', default=None) or 'production'
    sentry_release = config('SENTRY_RELEASE', default=None)

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(transaction_style='url'),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        traces_sample_rate=sentry_traces_sample_rate,
        send_default_pii=False,  # Don't send personally identifiable information
        environment=sentry_environment,
        release=sentry_release,
    )

# Security Headers & HTTPS Configuration
# Only enforce HTTPS in production (when DEBUG=False)
if not DEBUG:
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', cast=bool, default=None)
    if SECURE_SSL_REDIRECT is None:
        SECURE_SSL_REDIRECT = True

    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', cast=int, default=None)
    if SECURE_HSTS_SECONDS is None:
        SECURE_HSTS_SECONDS = 31536000  # 1 year

    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', cast=bool, default=None)
    if SECURE_HSTS_INCLUDE_SUBDOMAINS is None:
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', cast=bool, default=None)
    if SECURE_HSTS_PRELOAD is None:
        SECURE_HSTS_PRELOAD = True

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Additional security headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Proxy SSL header configuration (if behind reverse proxy)
SECURE_PROXY_SSL_HEADER = config(
    'SECURE_PROXY_SSL_HEADER',
    default=None
)
if SECURE_PROXY_SSL_HEADER:
    try:
        proto_header, expected_value = SECURE_PROXY_SSL_HEADER.split(', ')
        SECURE_PROXY_SSL_HEADER = (proto_header.strip(), expected_value.strip())
    except (ValueError, AttributeError):
        SECURE_PROXY_SSL_HEADER = None


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'users',
    'documents',
    'envelopes',
    'signatures',
    'fields',
    'notifications',
    'audit',
    'contacts',
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'esign.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'esign.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = config('DATABASE_URL', default=None)
if DATABASE_URL:
    default_db = dj_database_url.config(default=DATABASE_URL)
else:
    # Fallback to local SQLite when DATABASE_URL is not provided
    default_db = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

DATABASES = {
    'default': default_db
}

# Database connection pooling configuration
# CONN_MAX_AGE: Maximum age of database connections in seconds
# 0 = disable persistent connections (SQLite default)
# None = unlimited persistent connections (recommended for PostgreSQL)
if 'postgresql' in DATABASES['default'].get('ENGINE', ''):
    DB_CONN_MAX_AGE = config('DB_CONN_MAX_AGE', cast=int, default=None)
    if DB_CONN_MAX_AGE is None:
        DB_CONN_MAX_AGE = 600  # 10 minutes

    DATABASES['default']['CONN_MAX_AGE'] = DB_CONN_MAX_AGE
    # Connection pool settings
    DATABASES['default']['OPTIONS'] = {
        'connect_timeout': 10,
    }

# Cache configuration
try:
    import django_redis
    CACHE_BACKEND = config('CACHE_BACKEND', default=None)
    CACHE_LOCATION = config('CACHE_LOCATION', default=None)
    CACHE_TIMEOUT = config('CACHE_TIMEOUT', cast=int, default=None)

    if CACHE_BACKEND and CACHE_LOCATION:
        if CACHE_TIMEOUT is None:
            CACHE_TIMEOUT = 300  # 5 minutes default

        CACHES = {
            'default': {
                'BACKEND': CACHE_BACKEND,
                'LOCATION': CACHE_LOCATION,
                'OPTIONS': {
                    'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                    'SOCKET_CONNECT_TIMEOUT': 5,
                    'SOCKET_TIMEOUT': 5,
                    'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                    'IGNORE_EXCEPTIONS': True,  # Don't fail on cache errors
                },
                'KEY_PREFIX': 'esign',
                'TIMEOUT': CACHE_TIMEOUT,
            }
        }
    else:
        # If cache env vars are not provided, fall back to dummy cache
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
            }
        }
except ImportError:
    # Fallback to dummy cache if django-redis is not installed
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }

# Use SQLite for tests to avoid external DB dependencies
if 'pytest' in sys.modules:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'test_db.sqlite3',
        }
    }


# Django REST Framework
PAGE_SIZE = config('PAGE_SIZE', cast=int, default=None)
if PAGE_SIZE is None:
    PAGE_SIZE = 20

THROTTLE_RATE_ANON = config('THROTTLE_RATE_ANON', default=None) or '100/hour'
THROTTLE_RATE_USER = config('THROTTLE_RATE_USER', default=None) or '1000/hour'
THROTTLE_RATE_AUTH = config('THROTTLE_RATE_AUTH', default=None) or '10/minute'
THROTTLE_RATE_UPLOAD = config('THROTTLE_RATE_UPLOAD', default=None) or '20/hour'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': PAGE_SIZE,
    'PAGE_SIZE_QUERY_PARAM': 'page_size',
    'MAX_PAGE_SIZE': 100,
    # Rate limiting/throttling
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': THROTTLE_RATE_ANON,
        'user': THROTTLE_RATE_USER,
        'auth': THROTTLE_RATE_AUTH,    # For login/register
        'upload': THROTTLE_RATE_UPLOAD,  # For file uploads
    },
}

# CORS configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    cast=Csv(),
    default=None
)

# Additional CORS settings for file uploads
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only in development - never in production
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = config('FILE_UPLOAD_MAX_MEMORY_SIZE', cast=int, default=None)
if FILE_UPLOAD_MAX_MEMORY_SIZE is None:
    FILE_UPLOAD_MAX_MEMORY_SIZE = 26214400  # 25MB

DATA_UPLOAD_MAX_MEMORY_SIZE = config('DATA_UPLOAD_MAX_MEMORY_SIZE', cast=int, default=None)
if DATA_UPLOAD_MAX_MEMORY_SIZE is None:
    DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400  # 25MB

DATA_UPLOAD_MAX_NUMBER_FIELDS = config('DATA_UPLOAD_MAX_NUMBER_FIELDS', cast=int, default=None)
if DATA_UPLOAD_MAX_NUMBER_FIELDS is None:
    DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = config('STATIC_URL', default=None) or '/static/'
STATIC_ROOT = config('STATIC_ROOT', default=None) or (BASE_DIR / 'staticfiles')
STATICFILES_DIRS = []

# Media files (User uploads)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = config('MEDIA_URL', default=None) or '/media/'

# Always resolve MEDIA_ROOT to an absolute path, even when provided as a
# relative value via environment configuration (e.g., MEDIA_ROOT=media).
media_root_config = config('MEDIA_ROOT', default=None)
if media_root_config:
    media_root_path = Path(media_root_config)
    if not media_root_path.is_absolute():
        media_root_path = BASE_DIR / media_root_path
else:
    media_root_path = BASE_DIR / 'media'

MEDIA_ROOT = media_root_path

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# File storage
# Use S3 in production if configured, otherwise use local storage
USE_S3 = config('USE_S3', cast=bool, default=None)
if USE_S3 is None:
    USE_S3 = False

if USE_S3:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'
    
    # AWS S3 configuration
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default=None)
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default=None)
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default=None)
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default=None)
    AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default=None)
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_DEFAULT_ACL = 'private'
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = True
else:
    # Development: use local file system storage (default)
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    # AWS variables still available for optional use
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default=None)
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default=None)
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default=None)
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default=None)


# Custom user model
AUTH_USER_MODEL = 'users.CustomUser'

# Simple JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),  # Increased from 5 minutes to 8 hours for better UX
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Increased from 1 day to 7 days
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND')
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_IMPORTS = ('notifications.tasks',)

# Celery task settings
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

# Email configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default=None) or 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default=None) or 'smtp.gmail.com'

EMAIL_PORT = config('EMAIL_PORT', cast=int, default=None)
if EMAIL_PORT is None:
    EMAIL_PORT = 587

EMAIL_HOST_USER = config('EMAIL_HOST_USER', default=None) or ''
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default=None) or ''

EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool, default=None)
if EMAIL_USE_TLS is None:
    EMAIL_USE_TLS = True

EMAIL_USE_SSL = config('EMAIL_USE_SSL', cast=bool, default=None)
if EMAIL_USE_SSL is None:
    EMAIL_USE_SSL = False

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=None) or 'no-reply@incel-esign.local'
FRONTEND_BASE_URL = config('FRONTEND_BASE_URL', default=None)

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            'format': '{"time": "%(asctime)s", "name": "%(name)s", "level": "%(levelname)s", "message": "%(message)s", "pathname": "%(pathname)s", "lineno": %(lineno)d}',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose' if DEBUG else 'json',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'filters': ['require_debug_false'],
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django_errors.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'] if not DEBUG else ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['error_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'documents': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'envelopes': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'signatures': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'audit': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'notifications': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Ensure logs directory exists
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)
