# Generated by Django 5.2.6 on 2025-09-16 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envelopes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the signature.', primary_key=True, serialize=False)),
                ('signature_image', models.TextField(blank=True, help_text='Base64 encoded signature image or signature data.', null=True)),
                ('signed_at', models.DateTimeField(blank=True, help_text='Timestamp when the signature was completed.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('declined', 'Declined')], default='pending', help_text='Current status of the signature.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the signature record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the signature record was last updated.')),
                ('envelope', models.ForeignKey(help_text='The envelope this signature belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='envelopes.envelope')),
                ('signer', models.ForeignKey(help_text='The user who needs to sign this document.', on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
                'ordering': ['created_at'],
                'unique_together': {('envelope', 'signer')},
            },
        ),
    ]
