# Generated by Django 5.2.6 on 2025-09-17 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0003_envelope_envelopes_e_creator_8b1593_idx_and_more'),
        ('signatures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user signature.', primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='The signature image file.', upload_to='user_signatures/')),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default signature.")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the signature was created.')),
            ],
            options={
                'verbose_name': 'User Signature',
                'verbose_name_plural': 'User Signatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['envelope', 'status'], name='signatures__envelop_4a6087_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['signer', 'status'], name='signatures__signer__099b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['status'], name='signatures__status_44f6b9_idx'),
        ),
        migrations.AddField(
            model_name='usersignature',
            name='user',
            field=models.ForeignKey(help_text='The user who owns this signature.', on_delete=django.db.models.deletion.CASCADE, related_name='user_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usersignature',
            index=models.Index(fields=['user', 'is_default'], name='signatures__user_id_34c13f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersignature',
            index=models.Index(fields=['user', 'created_at'], name='signatures__user_id_62dbbd_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersignature',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_signature_per_user'),
        ),
    ]
