# Generated by Django 5.2.6 on 2026-07-01 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0012_seed_self_signed_envelope_status'),
        ('signatures', '0002_usersignature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('signed', 'Signed'), ('declined', 'Declined')], default='pending', help_text='Current status of the signature.', max_length=20),
        ),
        migrations.CreateModel(
            name='SigningJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('signing_version', models.PositiveIntegerField(default=1)),
                ('signature_image_data', models.TextField(blank=True, default='')),
                ('fallback_placement', models.JSONField(blank=True, default=dict)),
                ('is_self_sign', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_jobs', to='envelopes.envelope')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signing_jobs', to='signatures.signature')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['envelope', 'signer', 'status'], name='signatures__envelop_9ac6e3_idx'), models.Index(fields=['status', 'created_at'], name='signatures__status_7a2763_idx')],
            },
        ),
    ]
